/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author UNIVASSOURAS
 */
public class Interacao extends javax.swing.JFrame {

    /**
     * Creates new form Interacao
     */
    public Interacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitleCadastro = new javax.swing.JLabel();
        labelTitleInteracao = new javax.swing.JLabel();
        txtMensagem2 = new javax.swing.JTextField();
        labelNome2 = new javax.swing.JLabel();
        labelSobrenome2 = new javax.swing.JLabel();
        labelMensagem2 = new javax.swing.JLabel();
        txtSobrenome2 = new javax.swing.JTextField();
        txtNome2 = new javax.swing.JTextField();
        btnLimpar2 = new javax.swing.JButton();
        btnEnviar2 = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();

        labelTitleCadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitleCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleCadastro.setText("Cadastro");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitleInteracao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitleInteracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleInteracao.setText("Interação");

        labelNome2.setText("Nome:");

        labelSobrenome2.setText("Sobrenome:");

        labelMensagem2.setText("Mensagem:");

        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fechar.png"))); // NOI18N
        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });

        btnEnviar2.setBackground(new java.awt.Color(0, 86, 0));
        btnEnviar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lapis.png"))); // NOI18N
        btnEnviar2.setText("Enviar");
        btnEnviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar2ActionPerformed(evt);
            }
        });

        btnSair2.setBackground(new java.awt.Color(86, 0, 0));
        btnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair (2).png"))); // NOI18N
        btnSair2.setText("Sair");
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleInteracao, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnSair2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelSobrenome2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(labelMensagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSobrenome2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(61, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleInteracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar2)
                    .addComponent(btnEnviar2)
                    .addComponent(btnSair2))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome2)
                        .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSobrenome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSobrenome2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMensagem2)
                        .addComponent(txtMensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    public void limparCampos() {
        txtNome2.setText("");
        txtSobrenome2.setText("");
        txtMensagem2.setText("");
        txtNome2.requestFocus();
    }
    
    private void btnEnviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar2ActionPerformed
        validar();
    }//GEN-LAST:event_btnEnviar2ActionPerformed

    public void validar() {
        if (txtNome2.getText().equals("")) {
            showMessageDialog(null, "O campo 'Nome' é obrigatório!", "Validação", JOptionPane.ERROR_MESSAGE);
            txtNome2.requestFocus();
        }
        else if (txtSobrenome2.getText().equals("")) {
            showMessageDialog(null, "O campo 'Sobrenome' é obrigatório!", "Validação", JOptionPane.ERROR_MESSAGE);
            txtSobrenome2.requestFocus();
        }
        else if (txtMensagem2.getText().equals("")) {
            showMessageDialog(null, "O campo 'Mensagem' é obrigatório!", "Validação", JOptionPane.ERROR_MESSAGE);
            txtMensagem2.requestFocus();
        }
        else {
            String msg = txtNome2.getText() + " " + txtSobrenome2.getText() + "\nMensagem: " + txtMensagem2.getText();
            showMessageDialog(null, msg, "Interação", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        }
    }
    
    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSair2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar2;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnSair2;
    private javax.swing.JLabel labelMensagem2;
    private javax.swing.JLabel labelNome2;
    private javax.swing.JLabel labelSobrenome2;
    private javax.swing.JLabel labelTitleCadastro;
    private javax.swing.JLabel labelTitleInteracao;
    private javax.swing.JTextField txtMensagem2;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtSobrenome2;
    // End of variables declaration//GEN-END:variables
}
