/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Desktop
 */
public class TelaPacientes extends javax.swing.JFrame {

    /**
     * Creates new form Tela02
     */
    public TelaPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomePaciente = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelTelFixo = new javax.swing.JLabel();
        labelCel = new javax.swing.JLabel();
        labelEmailPaciente = new javax.swing.JLabel();
        labelConvenio = new javax.swing.JLabel();
        labelObservacao = new javax.swing.JLabel();
        labelDentista = new javax.swing.JLabel();
        labelFiltrarnome = new javax.swing.JLabel();
        txtNumPaciente = new javax.swing.JTextField();
        txtNomePaciente = new javax.swing.JTextField();
        txtEnderecoPaciente = new javax.swing.JTextField();
        txtTelFixo = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        txtEmailPaciente = new javax.swing.JTextField();
        txtConvenio = new javax.swing.JTextField();
        txtObservacao = new javax.swing.JTextField();
        txtDentista = new javax.swing.JTextField();
        labelPacientes = new javax.swing.JLabel();
        txtFiltarNome = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelRegiao = new javax.swing.JLabel();
        comboRegiaoPaciente = new javax.swing.JComboBox<>();
        btnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        scrollPanePaciente = new javax.swing.JScrollPane();
        listPacientes = new javax.swing.JList<>();
        labelNumPacientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pacientes");

        labelNomePaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelNomePaciente.setText("Nome do paciente");
        labelNomePaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        labelEndereco.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelEndereco.setText("Endereço");

        labelTelFixo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTelFixo.setText("Telefone Fixo");

        labelCel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelCel.setText("Celular");

        labelEmailPaciente.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelEmailPaciente.setText("Email");

        labelConvenio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelConvenio.setText("Convênio");

        labelObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelObservacao.setText("Observações");

        labelDentista.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelDentista.setText("Dentista");

        labelFiltrarnome.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelFiltrarnome.setText("Filtrar pacientes pelo nome");

        txtNumPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPacienteActionPerformed(evt);
            }
        });

        txtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePacienteActionPerformed(evt);
            }
        });

        labelPacientes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelPacientes.setText("Relação de paciente");
        labelPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtFiltarNome.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtFiltarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltarNomeActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair (2).png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imprimir.png"))); // NOI18N
        btnImprimir.setText("Imprimir");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lixeira-de-reciclagem.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);

        labelRegiao.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelRegiao.setText("Região");

        comboRegiaoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre  AC", "Alagoas  AL", "Amapá  AP", "Amazonas  AM", "Bahia  BA", "Ceará  CE", "Espírito Santo  ES", "Goiás  GO", "Maranhão  MA", "Mato Grosso  MT", "Mato Grosso do Sul  MS", "Minas Gerais  MG", "Pará  PA", "Paraíba  PB", "Paraná  PR", "Pernambuco  PE", "Piauí  PI", "Rio de Janeiro  RJ", "Rio Grande do Norte  RN", "Rio Grande do Sul  RS", "Rondônia  RO", "Roraima  RR", "Santa Catarina  SC", "São Paulo  SP", "Sergipe  SE", "Tocantins  TO", "Distrito Federal  DF" }));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lapis.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionar-ficheiro.png"))); // NOI18N
        btnIncluir.setText("Incluir");

        scrollPanePaciente.setViewportView(listPacientes);

        labelNumPacientes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelNumPacientes.setText("Numero de Registros dos pacientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelFiltrarnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtFiltarNome)
                                .addGap(45, 45, 45)))
                        .addComponent(btnIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPanePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(labelPacientes)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumPacientes)
                            .addComponent(labelTelFixo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNomePaciente)
                                    .addComponent(txtNumPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEndereco)
                                    .addComponent(txtEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(labelRegiao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(comboRegiaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCel)
                                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelEmailPaciente)
                            .addComponent(labelConvenio)
                            .addComponent(labelDentista)
                            .addComponent(txtDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelObservacao)
                            .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomePaciente)
                            .addComponent(labelRegiao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRegiaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelFixo)
                            .addComponent(labelCel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelFixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEmailPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelConvenio)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDentista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelObservacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnExcluir)
                            .addComponent(btnImprimir)
                            .addComponent(btnAlterar)
                            .addComponent(btnIncluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFiltrarnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPacienteActionPerformed

    private void txtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePacienteActionPerformed

    private void txtFiltarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltarNomeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> comboRegiaoPaciente;
    private javax.swing.JLabel labelCel;
    private javax.swing.JLabel labelConvenio;
    private javax.swing.JLabel labelDentista;
    private javax.swing.JLabel labelEmailPaciente;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelFiltrarnome;
    private javax.swing.JLabel labelNomePaciente;
    private javax.swing.JLabel labelNumPacientes;
    private javax.swing.JLabel labelObservacao;
    private javax.swing.JLabel labelPacientes;
    private javax.swing.JLabel labelRegiao;
    private javax.swing.JLabel labelTelFixo;
    private javax.swing.JList<String> listPacientes;
    private javax.swing.JScrollPane scrollPanePaciente;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtDentista;
    private javax.swing.JTextField txtEmailPaciente;
    private javax.swing.JTextField txtEnderecoPaciente;
    private javax.swing.JTextField txtFiltarNome;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtNumPaciente;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtTelFixo;
    // End of variables declaration//GEN-END:variables
}
